### ISSUE TITLE
FileNotFoundError using !include

### ISSUE THREAD

**Issue by gerard33** [robmarkcole/HASS-data-detective#87]
When running All Cells I get the following error
```
FileNotFoundError: [Errno 2] No such file or directory: '/config/includes/lights/includes/lights/lights.yaml'
```

The lights.yaml file is in `/config/includes/lights` so it seems to add the folder twice.

The relevant config.yaml part
```yaml
automation: !include_dir_merge_list automation/
hue: !include includes/lights/hue.yaml
light: !include includes/lights/lights.yaml
```

I also got the message `YAML tag !include_dir_merge_list is not supported` but guess that's not an issue.
