### ISSUE TITLE
MariaDB query error

### ISSUE THREAD

**Issue by DavidFW1960** [robmarkcole/HASS-data-detective#91]
I am getting this error when I try and follow the getting started workbook:
```
YAML tag !include_dir_named is not supported
Successfully connected to database mysql://hassmaria:***@core-mariadb/homeassistant
Error with query: 
            SELECT entity_id
            FROM states
            GROUP BY entity_id
            
(_mysql_exceptions.OperationalError) (2006, "Host 'addon_a0d7b954_jupyterlablite.hassio' is not allowed to connect to this MariaDB server") (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by robmarkcole** [comment]
I'm assuming you are using `db = db_from_hass_config() # Auto detect`?
From reading the [addon docs](https://www.home-assistant.io/addons/mariadb/) I'm guessing that whichever user profile is accessing the db does not have sufficient rights to query the db.

**Comment by robmarkcole** [comment]
Well it looks like host is `addon_a0d7b954_jupyterlablite.hassio` from your error message. I will setup the mariadb addon and try to reproduce.  Would be good to get these common setup challenges solved

**Comment by robmarkcole** [comment]
OK well it works fine for me, no sure whats wrong in your case

![image](https://user-images.githubusercontent.com/11855322/50546361-929fa900-0c1e-11e9-865b-b50950d0c977.png)

I've configured the addon with:
```yaml
{
  "databases": [
    "homeassistant"
  ],
  "logins": [
    {
      "username": "hass",
      "host": "%",
      "password": "somepassword"
    }
  ],
  "rights": [
    {
      "username": "hass",
      "host": "%",
      "database": "homeassistant",
      "grant": "ALL PRIVILEGES ON"
    }
  ]
}
```
